### ISSUE TITLE
Image download crashing when confronted with an http 404 'not found' situation

### ISSUE THREAD

**Issue by willfull** [Ainias/beyondPrinting#2]
Hi there!  First of all, thank you for putting this together - I was excited to find out such a utility exists.  I tried it out this weekend to build some PDF archives of purchased books and adventures.  Everything seemed to run fine - downloaded the three core handbooks, a few supplementals, a few adventures - until my attempt to back-up _Bigby Presents: Glory of the Giants_.

At first, everything is working fine, until this happens:

>  ![image](https://github.com/Ainias/beyondPrinting/assets/990768/54f09dde-d149-42eb-a1b2-ca1d1caf7a4b)

It just **froze** at this point.  Refreshes, restarts... nothing would resolve past this point.

I took a quick peek at the console in DevTools, and I see this:

>  ![image](https://github.com/Ainias/beyondPrinting/assets/990768/c6ba047f-dc36-4be4-a50d-04d7728c2175)

... apparently there's an image missing from dndbeyond.com for _BP:GotG_.  (Can anyone else confirm this?)
How is your extension set up to handle http 404 'not found' errors during this step?

I know that an asset missing from the server is not your fault, but could there be an option added to settings where we could skip a missing image or whatever in favor of getting a finished PDF?  I'm paging through the document on Beyond looking for a missing picture, but have not found it yet (I had intended on reporting this omission to WotC).

Thanks for your work in building this utility!  It's looking very useful so far.

**Comment by Ainias** [comment]
I've just uploaded a new version, which is available inside the chrome store. It includes better errror handling (or error handling at all) and some bugfixes. Bigby's should work again.

**Comment by willfull** [comment]
Worked like a charm!  Thank you so much for the update, most appreciated.
